name: hackathon
description: "A new Flutter project."
publish_to: 'none' 


environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  page_view_sliding_indicator: ^0.0.4
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  flutter_staggered_grid_view: ^0.7.0
  flutter_rating_bar: ^4.0.1
  provider: ^6.1.2
  cloud_firestore: ^4.17.3
  image_picker: ^1.1.1
  firebase_storage: ^11.7.5
  
  


dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

 
  assets:
    - assets/images/
   
    # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
