// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAECXvVuO2qfxAUkFzSVSZFus-83R-8tvA',
    appId: '1:1082188331766:web:6d8a7a06a740a35f6fcad7',
    messagingSenderId: '1082188331766',
    projectId: 'hackathon-4a23f',
    authDomain: 'hackathon-4a23f.firebaseapp.com',
    storageBucket: 'hackathon-4a23f.appspot.com',
    measurementId: 'G-WCL2VRR84F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAlG-QnmkIWZYmfAlaV9YHqq7uYPlczO0',
    appId: '1:1082188331766:android:9fa9128e29009ee96fcad7',
    messagingSenderId: '1082188331766',
    projectId: 'hackathon-4a23f',
    storageBucket: 'hackathon-4a23f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAONLLlwxXnWr5Jg0L-SYyormhAbek64dw',
    appId: '1:1082188331766:ios:a955a6578b3633966fcad7',
    messagingSenderId: '1082188331766',
    projectId: 'hackathon-4a23f',
    storageBucket: 'hackathon-4a23f.appspot.com',
    iosBundleId: 'com.example.hackathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAONLLlwxXnWr5Jg0L-SYyormhAbek64dw',
    appId: '1:1082188331766:ios:a955a6578b3633966fcad7',
    messagingSenderId: '1082188331766',
    projectId: 'hackathon-4a23f',
    storageBucket: 'hackathon-4a23f.appspot.com',
    iosBundleId: 'com.example.hackathon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAECXvVuO2qfxAUkFzSVSZFus-83R-8tvA',
    appId: '1:1082188331766:web:f530b9aff64e4a956fcad7',
    messagingSenderId: '1082188331766',
    projectId: 'hackathon-4a23f',
    authDomain: 'hackathon-4a23f.firebaseapp.com',
    storageBucket: 'hackathon-4a23f.appspot.com',
    measurementId: 'G-3PLEHHVGXR',
  );
}
